import type { Metadata } from "next";
import "./globals.css";
import Header from "./componens/header";
import Footer from "./componens/footer";


export const metadata: Metadata = {
  title: "Hoa Van",
  description: "Generated by Hoa Van",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
